name: advisify
description: "A flutter project with clean architecture"
publish_to: "none"

version: 1.0.5+2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  dio: ^5.8.0+1
  http: ^1.2.1
  path: ^1.9.1
  intl: ^0.20.2
  get_it: ^8.0.3
  go_router: ^15.1.2
  file_picker: ^10.2.0
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.1.4
  riverpod_annotation: ^2.3.5
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.1.1

  # UI
  pinput: ^5.0.1
  fl_chart: ^1.0.0
  flutter_svg: ^2.1.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0

  # Utility
  phone_numbers_parser: ^9.0.3
  country_code_picker: ^3.3.0
  country_picker: ^2.0.27
#  firebase_core: ^3.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.15
  custom_lint_core: ^0.7.5
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/ellipse/
    - assets/icons/
    - assets/icons/payments/
    - assets/images/
    - assets/dummy/
    - assets/nav_icons/
    - assets/app_icons/app_icon_2.png

  fonts:
    - family: Segoe Pro
      fonts:
        - asset: fonts/segoe_pro/SegoePro-Light.ttf
          weight: 300
        - asset: fonts/segoe_pro/SegoePro-Regular.ttf
          weight: 400
        - asset: fonts/segoe_pro/SegoePro-Semibold.ttf
          weight: 600
        - asset: fonts/segoe_pro/SegoePro-Bold.ttf
          weight: 700
        - asset: fonts/segoe_pro/SegoePro-Black.ttf
          weight: 800

    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Light-BETA.otf
          weight: 300 # Light
        - asset: fonts/inter/Inter-Regular.otf
          weight: 400 # Regular
        - asset: fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.otf
          weight: 600 # SemiBold
        - asset: fonts/inter/Inter-Bold.otf
          weight: 700 # Bold
        - asset: fonts/inter/Inter-Black.otf
          weight: 800
